services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # React production build served via Nginx
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
